CREATE USER BOTTLEGREENTW IDENTIFIED BY "1234" DEFAULT TABLESPACE "USERS";

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE TO BOTTLEGREENTW;
