--------------------------------------------------------
--  DDL for Sequence MEAS_AI
--------------------------------------------------------

   CREATE SEQUENCE  "BOTTLEGREENTW"."MEAS_AI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRO_AI
--------------------------------------------------------

   CREATE SEQUENCE  "BOTTLEGREENTW"."PRO_AI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VEN_AI
--------------------------------------------------------

   CREATE SEQUENCE  "BOTTLEGREENTW"."VEN_AI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table MEASURES
--------------------------------------------------------

  CREATE TABLE "BOTTLEGREENTW"."MEASURES" 
   (	"ID" NUMBER(*,0), 
	"MEASURE_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "BOTTLEGREENTW"."PRODUCTS" 
   (	"ID" NUMBER(*,0), 
	"VENDOR_ID" NUMBER(*,0), 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"MEASURE_ID" NUMBER(*,0), 
	"PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENDORS
--------------------------------------------------------

  CREATE TABLE "BOTTLEGREENTW"."VENDORS" 
   (	"ID" NUMBER(*,0), 
	"VENDOR_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOTTLEGREENTW.MEASURES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOTTLEGREENTW"."PRODUCTS_PK" ON "BOTTLEGREENTW"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENDORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOTTLEGREENTW"."VENDORS_PK" ON "BOTTLEGREENTW"."VENDORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEASURES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOTTLEGREENTW"."MEASURES_PK" ON "BOTTLEGREENTW"."MEASURES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VENDORS
--------------------------------------------------------

  ALTER TABLE "BOTTLEGREENTW"."VENDORS" ADD CONSTRAINT "VENDORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOTTLEGREENTW"."VENDORS" MODIFY ("VENDOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOTTLEGREENTW"."VENDORS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" MODIFY ("MEASURE_ID" NOT NULL ENABLE);
  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEASURES
--------------------------------------------------------

  ALTER TABLE "BOTTLEGREENTW"."MEASURES" ADD CONSTRAINT "MEASURES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOTTLEGREENTW"."MEASURES" MODIFY ("MEASURE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOTTLEGREENTW"."MEASURES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_FK1" FOREIGN KEY ("MEASURE_ID")
	  REFERENCES "BOTTLEGREENTW"."MEASURES" ("ID") ENABLE;
  ALTER TABLE "BOTTLEGREENTW"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_FK2" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "BOTTLEGREENTW"."VENDORS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEASURES_AI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOTTLEGREENTW"."MEASURES_AI" 
BEFORE INSERT ON Measures
FOR EACH ROW

BEGIN
  SELECT meas_ai.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "BOTTLEGREENTW"."MEASURES_AI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTS_AI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOTTLEGREENTW"."PRODUCTS_AI" 
BEFORE INSERT ON PRODUCTS
FOR EACH ROW

BEGIN
  SELECT pro_ai.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "BOTTLEGREENTW"."PRODUCTS_AI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VENDORS_AI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOTTLEGREENTW"."VENDORS_AI" 
BEFORE INSERT ON Vendors
FOR EACH ROW

BEGIN
  SELECT ven_ai.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "BOTTLEGREENTW"."VENDORS_AI" ENABLE;

INSERT INTO Measures (Measure_Name) VALUES ('millimeter');
INSERT INTO Measures (Measure_Name) VALUES ('centimeter');
INSERT INTO Measures (Measure_Name) VALUES ('decimeter ');
INSERT INTO Measures (Measure_Name) VALUES ('meter');
INSERT INTO Measures (Measure_Name) VALUES ('dekameter');
INSERT INTO Measures (Measure_Name) VALUES ('kilometer');


INSERT INTO Vendors (Vendor_Name) VALUES ('Linus');
INSERT INTO Vendors (Vendor_Name) VALUES ('Abbot');
INSERT INTO Vendors (Vendor_Name) VALUES ('Nero');
INSERT INTO Vendors (Vendor_Name) VALUES ('Mufutau');
INSERT INTO Vendors (Vendor_Name) VALUES ('Reese');
INSERT INTO Vendors (Vendor_Name) VALUES ('Hilel');
INSERT INTO Vendors (Vendor_Name) VALUES ('Kenyon');
INSERT INTO Vendors (Vendor_Name) VALUES ('Colton');
INSERT INTO Vendors (Vendor_Name) VALUES ('Dalton');
INSERT INTO Vendors (Vendor_Name) VALUES ('Lester');

INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (1,'Zagorka',1,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (2,'Ariana',2,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (2,'Sandvich',1,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (1,'Liutenica',3,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (2,'Krenvirsh',4,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (3,'Kartofki',2,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (2,'Cigari',3,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (4,'Soleti',5,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (1,'Kafe',5,1);
INSERT INTO Products (Vendor_Id,Product_Name,Measure_Id,Price) VALUES (5,'Cola',1,1);
